Repository EC-CUBE/doc4.ec-cube.net, pull requests merged in 2020-06, with the labels that each got.

#97 CSSとSassについて、詳しく記載しました。
  _pages/design/css.md
Labels: Customize, installation

#98 CSSとSassの利用のmd記法の修正
  _data/navigation.yml
  _pages/design/css.md
  index.md
Labels: documentation

#100 プラグインインストール失敗時の対処法ページを作成しました。
  _data/navigation.yml
  _pages/plugin/error.md
  index.md
Labels: bug, installation

#105 アップデート手順書に4.0.4を追加
  _pages/quickstart/update.md
Labels: installation

#109 SameSite Cookieのドキュメントを更新
  _pages/quickstart/hotfix_samesite_cookie.md
Labels: installation

#110 開発者向けインストールの内容を補足＋α
  _data/navigation.yml
  _pages/quickstart/install.md
  _pages/quickstart/permission.md
  index.md
Labels: installation
