Repository EC-CUBE/doc4.ec-cube.net, pull requests merged in 2020-07, with the labels that each got.

#106 mock-package-apiについて記述
  _data/navigation.yml
  _pages/plugin/mock.md
  images/plugin/mock-server.png
  index.md
Labels: installation

#118 services.yamlのパスを修正
  _pages/plugin/spec.md
Labels: Customize

#120 タイポ修正 (forder -> folder)
  _pages/development-tools/mail-catcher.md
  _pages/i18n/currency.md
  _pages/i18n/debug_mode.md
  _pages/i18n/environmental_setting.md
  _pages/i18n/multilingualization.md
  _pages/i18n/timezone.md
  _pages/quickstart/cli.md
  _pages/quickstart/gui_mac_install.md
  _pages/quickstart/gui_win_install.md
  _pages/quickstart/install.md
  _pages/quickstart/permission.md
  _pages/quickstart/web-installer.md
Labels: documentation

#125 CSSとSassのページを分け、SassのページにはEC-CUBE4.0.4の内容も記載
  _data/navigation.yml
  _pages/design/css.md
  _pages/design/sass.md
  index.md
Labels: Customize

#127 Update install.md
  _pages/quickstart/install.md
Labels: installation

#117 Win環境のXAMPPインストール記事を4.0.4に対応
  _pages/quickstart/gui_win_install.md
  images/install/gui-win/step0.png
  images/install/gui-win/xampp1.png
Labels: installation

#129 運用者向け情報の表示位置を調整
  index.md
Labels: documentation
